#
# ğŸ›‘ Think twice before editing this file! ğŸ›‘
# âš ï¸ This file is maintained via https://github.com/IanStorm/dev-settings-sync. âš ï¸
#

# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Settings ğŸ”„ï¸

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Settings:
    uses: IanStorm/reusable-workflows/.github/workflows/_settings.yml@main
